FROM python:3.8

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN mkdir /code
WORKDIR /code

ADD requirements/base.txt \
    requirements/dev.txt \
    /code/requirements/
RUN pip3 install -r requirements/dev.txt

ADD . /code/
RUN useradd -m app
USER app
